// {
// "creator": "Maestro",
// "forceModifier1": "OFF",
// "forceModifier2": "OFF",
// "forceMissile1": "FALCON",
// "forceMissile2": "MISSILE POD",
// "forceWeapon1": "DRILLER",
// "forceWeapon2": "CRUSHER",
// "forceLoadout": "OFF",
// "powerupFilterBitmask": 65535,
// "powerupBigSpawn": "LOW",
// "powerupInitial": "NORMAL",
// "turnSpeedLimit": "MEDIUM",
// "powerupSpawn": "HIGH",
// "friendlyFire": false,
// "matchMode": "ANARCHY",
// "maxPlayers": 2,
// "showEnemyNames": "NORMAL",
// "timeLimit": 1200,
// "scoreLimit": 0,
// "respawnTimeSeconds": 2,
// "respawnShieldTimeSeconds": 2,
// "level": "SKYBOX V1.2",
// "joinInProgress": true,
// "rearViewAllowed": false,
// "teamCount": 2,
// "players": [ "MAESTRO" ],
// "name": "Stats",
// "type": "LobbyStatus"
// }